enma/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField, HiddenField, BooleanField
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from wtforms import ValidationError
from .models import User
from flask import flash


class EmailExists(object):
    """
    WTF Validator that checks if an email address already exists.

    via the exclude parameter a specific email addressed can be excluded
    from the check (i.e. the current email address of a user)
    """
    def __init__(self, exclude='', message='Email already registered'):
        self._exclude=exclude
        self._message = message

    def __call__(self, form, field):
        user = User.query.filter_by(email=field.data).first()
        if user and user.email != self._exclude:
            raise ValidationError(self._message)

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), EmailExists(),
                                Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        return True

class EditForm(Form):
    username = HiddenField('Username', validators=[])
    firstname = TextField('First Name', validators=[DataRequired(),
                            Length(min=2, max=40)])
    lastname = TextField('Last Name', validators=[DataRequired(),
                            Length(min=2, max=40)])
    email = TextField('Email', validators=[DataRequired(), Email(),
                            Length(min=6, max=40)])
    apply = SubmitField('Apply')

    def update_data(self, user=None):
        if user:
            self.username.data = user.username
            self.firstname.data = user.first_name
            self.lastname.data = user.last_name
            self.email.data = user.email

            

    def validate(self):
        initial_validation = super(EditForm, self).validate()
        if not initial_validation:
            return False
        return True

class DeleteForm(Form):
    username = HiddenField('Username', validators=[])
    safety_question = BooleanField('Do you really want to delete the user?',
                                  default = False)
    delete = SubmitField('Delete')

    def __init__(self, user=None, *args, **kwargs):
        super(DeleteForm, self).__init__(*args, **kwargs)
        print user
        if user:
            self.username.data = user.username

    def validate(self):
        if self.safety_question.data == 0:
            self.safety_question.errors = []
            self.safety_question.errors.append(
                "Please confirm by setting the checkmark")
            return False
        return True

class ChangePasswordForm(Form):
    username = HiddenField('username',)
    oldpassword = PasswordField('Old Password',
                        validators=[DataRequired(), Length(min=6, max=40)])
    password = PasswordField('Password',
                        validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password',
                                          message='Passwords must match')])
    setpwd = SubmitField('Set Password')

    def update_data(self, user):
        self.username.data = user.username

    def validate(self):
        flash('validate chpwd called', 'info')

        initial_validation = super(ChangePasswordForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("User does not exist")
            return False
        if not user.check_password(self.oldpassword.data):
            self.email.errors.append("Old password is wrong")
            return False
        return True

class ReadonlyTextField(TextField):
  def __call__(self, *args, **kwargs):
    kwargs.setdefault('readonly', True)
    return super(ReadonlyTextField, self).__call__(*args, **kwargs)

class RestTokenForm(Form):
    token = ReadonlyTextField('Access Token')
    expiry = ReadonlyTextField('Token Expiry')
    lifetime = SelectField('Token Lifetime', default='60',
                           choices=[('60', 'One Minute'),
                                    ('3600', 'One hour'),
                                    ('86400', 'One day'),
                                    ('2592000', '30 days')])

    generate = SubmitField('Generate new Token')

    def update_data(self, user):
        pass

enma/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template, request, jsonify
from enma.settings import ProdConfig
from enma.assets import assets
from enma.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
)
from enma import public, user, entitlement, rest


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(entitlement.views.blueprint)
    app.register_blueprint(rest.api)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        if request.accept_mimetypes.accept_json and \
                not request.accept_mimetypes.accept_html:
            if error_code == 401:
                response = jsonify({'error': 'unauthorized'})
            elif error_code == 404:
                response = jsonify({'error': 'not found'})
            elif error_code == 500:
                response = jsonify({'error': 'internal server error'})
            response.status_code = error_code
            return response
        if error_code == 405:
            response = jsonify({'error': 'method not supported'})
            response.status_code = error_code
            return response
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 405, 500]:
        app.errorhandler(errcode)(render_error)
    return None

enma/entitlement/__init__.py
# -*- coding: utf-8 -*-
""" The Entitlements Package """
from . import views

enma/entitlement/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, flash, redirect, url_for
from flask.ext.login import login_required, current_user, logout_user

from enma.user.models import User
from enma.user.forms import DeleteForm, EditForm, ChangePasswordForm
from enma.database import db
from enma.utils import flash_errors

blueprint = Blueprint("entitlement", __name__, url_prefix='/entitlements',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def list():
    return render_template("entitlements/list.html")

@blueprint.route("/requests")
@login_required
def requests():
    return render_template("entitlements/list.html")


@blueprint.route("/types")
@login_required
def types():
    return render_template("entitlements/types.html")

enma/rest/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix='/rest/v1.0')

from . import authentication, errors, views

enma/rest/views.py
# -*- coding: utf-8 -*-
'''Public section, including homepage and signup.'''
from flask import g, jsonify

from enma.extensions import auth
from . import api
from .errors import not_found


@api.route("/token", methods=["PUT"])
@auth.login_required
def token():
    return jsonify({
        'token': g.current_user.generate_auth_token(expiration=3600),
        'expiration': 3600}), 201


entitlements = [
    {
        'name': u'service-one',
        'type': u'service-one',
        'status': u'granted',
        'description': u'Use service one',
        'expiry': u'2014-09-20'
    },
    {
        'name': u'service-two',
        'type': u'service-two',
        'status': u'rewoked',
        'description': u'Use service two',
        'capacity': 500,
        'expiry': u'2014-09-20'
    },
]


@api.route('/entitlements', methods=['GET'])
@auth.login_required
def get_entitlements():
    """
    Respond with the list of all entitlements
    """
    return jsonify({'entitlements': entitlements})


@api.route('/entitlements/<name>', methods=['GET'])
@auth.login_required
def get_entitlement(name):
    """
    Respond with the granted i.e. valid entitlement by name or with
    404 - Not found 
    """
    tmp = filter(lambda x: x['name'] == name and x['status'] == 'granted',
                 entitlements)
    if len(tmp) == 0:
        return not_found('entitlement named %s' % name)
    return jsonify({'entitlements': tmp[0]})

enma/user/__init__.py
'''The user module.'''

from . import views

enma/user/views.py
# -*- coding: utf-8 -*-
import time
import datetime

from flask import Blueprint, render_template, flash, redirect, url_for
from flask import current_app
from flask.ext.login import login_required, current_user, logout_user

from enma.decorators import permission_required
from enma.user.models import User, Permission
from enma.user.forms import DeleteForm, EditForm, ChangePasswordForm
from enma.user.forms import RestTokenForm
from enma.database import db
from enma.utils import flash_errors


blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def home():
    current_app.logger.error('token called')

    return render_template("users/home.html")

@blueprint.route("/members")
@login_required
@permission_required(Permission.READ_USER)
def members():
    users = User.query.all()
    return render_template("users/members.html", users=users)


@blueprint.route("/delete/<name>",  methods=["GET", "POST"])
@login_required
def delete(name):
    user = User.query.filter_by(id=name).first()

    delete_form = DeleteForm(user=user, prefix='delete_form')
    if delete_form.delete.data:
        if delete_form.validate():
            db.session.delete(user)
            db.session.commit()
            if user == current_user:
                # delete yourself!!!
                logout_user()
                flash('You are removed from the system and logged out.', 'info')
                return redirect(url_for('public.home'))
            else:
                flash("User %s deleted" % str(user.username), 'info')
                return redirect(url_for('user.members'))
        else:
            flash_errors(delete_form)

    return render_template("users/delete.html", delete_form=delete_form )


@blueprint.route("/profile/<name>",  methods=["GET", "POST"])
@login_required
def profile(name):
    user = User.query.filter_by(id=name).first()
    
    edit_form = EditForm()
    if edit_form.apply.data:
        if edit_form.validate():
            user.first_name = edit_form.firstname.data
            user.last_name = edit_form.lastname.data
            user.email = edit_form.email.data
            db.session.add(user)
            db.session.commit()
            if user == current_user:
                flash('Your profile has been updated', 'info')
            else:
                flash('The profile of %s has been updated' % user.username,
                      'info')
        else:
            flash_errors(edit_form)
    edit_form.update_data(user)

    return render_template("users/profile.html", edit_form=edit_form)

@blueprint.route("/password",  methods=["GET", "POST"])
@login_required
def password():
    """
    Changing the password is only supported for the current user.
    """

    chpwd_form = ChangePasswordForm()
    if chpwd_form.setpwd.data:
        if chpwd_form.validate():
            current_user.set_password(chpwd_form.password.data)
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated', 'info')
        else:
            flash_errors(chpwd_form)
    chpwd_form.update_data(current_user)

    return render_template("users/password.html", chpwd_form=chpwd_form)


@blueprint.route("/token",  methods=["GET", "POST"])
@login_required
def token():
    """
    Manage the rest token
    """

    form = RestTokenForm()
    if form.generate.data:
        if form.validate():
            flash('Your token has been updated', 'info')
        else:
            flash_errors(form)
    expiry = time.time() + float(form.lifetime.data)
    form.expiry.data = datetime.datetime.fromtimestamp(expiry).strftime('%Y-%m-%d %H:%M:%S')
    form.token.data = current_user.generate_auth_token(expiry)
    return render_template("users/token.html", token_form=form)

enma/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

enma/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>©2014 Volker Kempert</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.terms') }}">Terms of Use</a></li>
      <li><a href="{{ url_for('public.privacy') }}">Privacy</a></li>
      <li><a href="{{ url_for('public.legal') }}">Legal Notice</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
      <li><a href="{{ url_for('public.contact') }}">Contact</a></li>
    </ul>
  </small>
</footer>

enma/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Entitlement Management
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  
  <link rel="stylesheet" href="/static/libs/bootstrap/dist/css/bootstrap.css">
  <link rel="stylesheet" href="/static/css/style.css">


  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}


<!-- JavaScript at the bottom for fast page loading -->
    <script type="text/javascript" src="/static/libs/jQuery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/libs/bootstrap/dist/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/plugins.js"></script>
    
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

enma/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">
        <i class="fa fa-home"></i></a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        {% if current_user and current_user.is_authenticated() %}
            <li><a class="navbar-link" href="{{ url_for('user.home') }}">
                <i class="fa fa-tachometer"></i> Dashboard </a></li>
            {% if current_user.is_administrator() %}
            <li><a class="navbar-link" href="{{ url_for('user.members') }}">
                <i class="fa fa-users"></i> Users</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-certificate"></i> Entitlements
                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('entitlement.types') }}"> Entitlement Types</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('entitlement.requests') }}"> Grant Request </a></li>
                <li><a href="{{ url_for('entitlement.list') }}"> All Entitlements </a></li>
              </ul>
            </li>

            {% endif %}
        {% endif %}
      <li><a href="{{ url_for('public.help') }}"><i class="fa fa-question-circle"></i> Help</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-gear"></i> {{ current_user.username }}
            <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">Your Settings</li>
            <li><a href="{{ url_for('user.profile', name=current_user.id) }}"><i class="fa fa-edit"></i> Profile</a></li>
            <li><a href="{{ url_for('user.token') }}"><i class="fa fa-tag"></i> REST Token</a></li>
            <li class="divider"></li>
            <li><a href="{{ url_for('user.password') }}"><i class="fa fa-key"></i> Change Password</a></li>
            <li class="divider"></li>
            <li><a href="{{ url_for('user.delete', name=current_user.id) }}"><i class="fa fa-trash-o"></i> Delete Account</a></li>
          </ul>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>